version: '3'

services:
  jwt-sample:
    container_name: jwt-sample
    image: node:12-alpine
    restart: always
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      MONGODB_URI: mongodb://mongo
      REDIS_HOST: redis
    command: yarn start
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '!@#MONGO'
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: '!@#MONGO'

  redis:
    container_name: redis
    image: redis:6-alpine
    restart: always
    hostname: redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8088:8081
